apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGI6MjcwMTcvbXVjaHRvZG8/YXV0aFNvdXJjZT1hZG1pbg==
  jwt-secret-key: bXVjaHRvZG8tZGV2LWp3dC1zZWNyZXQta2V5LWNoYW5nZS1tZQ==
